// Generated by scripts/build-array-audio.mjs. Offsets match both encoded banks.
export const ARRAY_SOUNDS = {
  "metal": [
    {
      "offset": 0,
      "duration": 0.72
    },
    {
      "offset": 0.78,
      "duration": 0.72
    }
  ],
  "wood": [
    {
      "offset": 1.56,
      "duration": 0.7
    },
    {
      "offset": 2.3200000000000003,
      "duration": 0.7
    }
  ],
  "water": [
    {
      "offset": 3.08,
      "duration": 0.92
    },
    {
      "offset": 4.0600000000000005,
      "duration": 0.92
    }
  ],
  "fire": [
    {
      "offset": 5.040000000000001,
      "duration": 0.82
    },
    {
      "offset": 5.920000000000001,
      "duration": 0.82
    }
  ],
  "earth": [
    {
      "offset": 6.800000000000001,
      "duration": 1.1
    },
    {
      "offset": 7.960000000000001,
      "duration": 1.1
    }
  ],
  "steam": [
    {
      "offset": 9.120000000000001,
      "duration": 1
    },
    {
      "offset": 10.180000000000001,
      "duration": 1
    }
  ],
  "splinter": [
    {
      "offset": 11.240000000000002,
      "duration": 0.78
    },
    {
      "offset": 12.080000000000002,
      "duration": 0.78
    }
  ],
  "rupture": [
    {
      "offset": 12.920000000000002,
      "duration": 0.95
    },
    {
      "offset": 13.930000000000001,
      "duration": 0.95
    }
  ],
  "melt": [
    {
      "offset": 14.940000000000001,
      "duration": 1
    },
    {
      "offset": 16,
      "duration": 1
    }
  ],
  "mud": [
    {
      "offset": 17.06,
      "duration": 0.94
    },
    {
      "offset": 18.06,
      "duration": 0.94
    }
  ],
  "ready": [
    {
      "offset": 19.06,
      "duration": 0.4
    },
    {
      "offset": 19.52,
      "duration": 0.4
    }
  ],
  "transfer": [
    {
      "offset": 19.98,
      "duration": 0.38
    },
    {
      "offset": 20.42,
      "duration": 0.38
    }
  ],
  "harmony": [
    {
      "offset": 20.860000000000003,
      "duration": 1.5
    },
    {
      "offset": 22.42,
      "duration": 1.5
    }
  ],
  "echo": [
    {
      "offset": 23.98,
      "duration": 0.6
    },
    {
      "offset": 24.64,
      "duration": 0.6
    }
  ],
  "remnant": [
    {
      "offset": 25.3,
      "duration": 0.5
    },
    {
      "offset": 25.86,
      "duration": 0.5
    }
  ],
  "mark": [
    {
      "offset": 26.419999999999998,
      "duration": 0.34
    },
    {
      "offset": 26.819999999999997,
      "duration": 0.34
    }
  ]
} as const;
export type ArraySound = keyof typeof ARRAY_SOUNDS;
