// Generated by scripts/build-forest-audio.mjs. Original score; CC0 instrument credits in public/audio.
export const AUDIO_REVISION = 'bcd4912b5166';
export const AUDIO_TRACKS = {
  "night-theme": {
    "seconds": 120,
    "channels": 2
  },
  "war-drums": {
    "seconds": 120,
    "channels": 1
  },
  "tightening-strings": {
    "seconds": 120,
    "channels": 1
  },
  "wind": {
    "seconds": 12,
    "channels": 2
  },
  "river": {
    "seconds": 12,
    "channels": 2
  },
  "embers": {
    "seconds": 12,
    "channels": 2
  },
  "forest-cues": {
    "seconds": 35.84,
    "channels": 1
  }
} as const;
export const SOUND_CUES = {
  "ui": {
    "offset": 0.1,
    "duration": 0.18
  },
  "choose": {
    "offset": 0.4,
    "duration": 0.6
  },
  "repair": {
    "offset": 1.12,
    "duration": 0.8
  },
  "reward": {
    "offset": 2.04,
    "duration": 2.3
  },
  "victory": {
    "offset": 4.46,
    "duration": 5.2
  },
  "defeat": {
    "offset": 9.78,
    "duration": 2.4
  },
  "camp-hit": {
    "offset": 12.3,
    "duration": 0.3
  },
  "danger": {
    "offset": 12.72,
    "duration": 0.85
  },
  "footstep": {
    "offset": 13.69,
    "duration": 0.16
  },
  "bite": {
    "offset": 13.97,
    "duration": 0.48
  },
  "wolf-death": {
    "offset": 14.57,
    "duration": 0.65
  },
  "elite-death": {
    "offset": 15.34,
    "duration": 1.1
  },
  "king": {
    "offset": 16.56,
    "duration": 2.6
  },
  "swift": {
    "offset": 19.28,
    "duration": 0.55
  },
  "giant": {
    "offset": 19.95,
    "duration": 0.65
  },
  "regen": {
    "offset": 20.72,
    "duration": 0.6
  },
  "rage": {
    "offset": 21.44,
    "duration": 1.3
  },
  "split": {
    "offset": 22.86,
    "duration": 0.85
  },
  "howl": {
    "offset": 23.83,
    "duration": 2
  },
  "seal": {
    "offset": 25.95,
    "duration": 1.5
  },
  "break": {
    "offset": 27.57,
    "duration": 1.25
  },
  "interrupt": {
    "offset": 28.94,
    "duration": 0.55
  },
  "formation-set": {
    "offset": 29.61,
    "duration": 0.45
  },
  "invoke-metal": {
    "offset": 30.18,
    "duration": 0.48
  },
  "invoke-wood": {
    "offset": 30.78,
    "duration": 0.48
  },
  "invoke-water": {
    "offset": 31.38,
    "duration": 0.48
  },
  "invoke-fire": {
    "offset": 31.98,
    "duration": 0.48
  },
  "invoke-earth": {
    "offset": 32.58,
    "duration": 0.48
  },
  "impact": {
    "offset": 33.18,
    "duration": 0.2
  },
  "time-stop": {
    "offset": 33.5,
    "duration": 1.1
  },
  "time-release": {
    "offset": 34.72,
    "duration": 1
  }
} as const;
export type SoundCue = keyof typeof SOUND_CUES;
export type AudioTrack = keyof typeof AUDIO_TRACKS;
export const SCORE_BAR = 2.5;
